# Generated by Django 5.1.3 on 2024-12-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_fun', '0004_alter_userprofile_bio_alter_userprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
